CREATE DATABASE `qr_code`;

USE `qr_code`;

CREATE TABLE `message`(
	`id` INT NOT NULL AUTO_INCREMENT COMMENT "ID",
	`uuid` CHAR(40) NOT NULL COMMENT "客户端标识",
	`message` VARCHAR(1024) NOT NULL DEFAULT "" COMMENT "文本内容",
	`sign` VARCHAR(6) NOT NULL COMMENT "短链标识",
	`create_time` DATETIME NOT NULL COMMENT "内容创建时间",
	CONSTRAINT `PRIMARY` PRIMARY KEY (`id`),
	UNIQUE (sign)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='文本表';


CREATE TABLE `image`(
	`id` INT NOT NULL AUTO_INCREMENT COMMENT "ID",
	`uuid` CHAR(40) NOT NULL COMMENT "客户端标识",
	`img_path` VARCHAR(64) NOT NULL DEFAULT "" COMMENT "图片路径",
	`sign` VARCHAR(6) NOT NULL COMMENT "短链标识",
	`create_time` DATETIME NOT NULL COMMENT "内容创建时间",
	CONSTRAINT `PRIMARY` PRIMARY KEY (`id`),
	UNIQUE (sign)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='图片表';


CREATE TABLE `url`(
	`id` INT NOT NULL AUTO_INCREMENT COMMENT "ID",
	`uuid` CHAR(40) NOT NULL COMMENT "客户端标识",
	`url` VARCHAR(4096) NOT NULL DEFAULT "" COMMENT "长链接",
	`hash` CHAR(32) NOT NULL COMMENT "url 哈希值，用于查找",
	`sign` VARCHAR(6) NOT NULL COMMENT "短链标识",
	`create_time` DATETIME NOT NULL COMMENT "内容创建时间",
	CONSTRAINT `PRIMARY` PRIMARY KEY (`id`),
	UNIQUE (sign),
	INDEX `url` (`hash`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='长链表';